# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

processInstances <- function(mu, x, lambda) {
    .Call('_dpmclust_processInstances', PACKAGE = 'dpmclust', mu, x, lambda)
}

euclideanDistance <- function(u, v) {
    .Call('_dpmclust_euclideanDistance', PACKAGE = 'dpmclust', u, v)
}

euclideanDistances <- function(u, v) {
    .Call('_dpmclust_euclideanDistances', PACKAGE = 'dpmclust', u, v)
}

